name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOPATH: ${{ github.workspace }}
  WORKSPACE: ${{ github.workspace }}/src/github.com/${{ github.repository }}
  GO111MODULE: on

jobs:

  setup:
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE }}

      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-



      - name: pwd
        run: pwd && echo $GOPATH

      - name: run main
        run: go run main.go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

 #     - name: Upload coverage to Codecov
 #       if: success() && matrix.go == 1.15 && matrix.os == 'ubuntu-latest'
 #       uses: codecov/codecov-action@v1
 #       with:
 #         token:
 #         fail_ci_if_error: false

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ${{ env.WORKSPACE }}
