name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WORKSPACE: ${{ github.workspace }}/src/github.com/${{ github.repository }}

jobs:

  setup:
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE }}

      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

#     - name: Set GOPATH and PATH
#       run: |
#         echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
#         echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
#       shell: bash

#     - name: Set build variables
#       run: |
#         echo "GOPROXY=https://proxy.golang.org" >> $GITHUB_ENV
#         echo "GO111MODULE=on" >> $GITHUB_ENV


      - name: pwd
        run: pwd && echo $GOPATH

      - name: run main
        run: go run main.go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
